### PR TITLE
fix: Resolve #508 — UI Walkthrough Bugs & UX Improvements (April 2026)

### LINKED ISSUE #508: [Epic] UI Walkthrough — Bugs & UX Issues (April 2026)
## UI Walkthrough Report — April 13, 2026

Comprehensive walkthrough of all 13 pages in the Talos application at `http://localhost:3001`. Every page was visited, forms and interactive elements tested, console errors checked, and screenshots taken.

### Summary

- **Pages Visited**: 13/13 (all pages)
- **Navigation**: All links and dropdowns work correctly
- **Console Errors**: React hydration mismatch on Chat page; favicon 404
- **Critical Security Bug**: 1 (API tokens displayed in plain text)
- **High Severity Bugs**: 5 (duplicate data, dark mode broken, chat messages not loading)
- **Medium UX Issues**: 5
- **Low UX Issues**: 4

### Pages Visited

| Page | URL | Status | Bugs |
|------|-----|--------|------|
| Dashboard | /talos | ✅ Works | Minor: DB names concatenated, favicon 404 |
| Chat | /chat | ⚠️ Issues | Hydration error, messages don't load, raw session IDs |
| Workbench | /workbench | ✅ Works | None |
| Test Library | /talos/tests | ✅ Works | None |
| Vault Roles | /talos/vault | ✅ Works | None |
| Artifacts | /talos/artifacts | ✅ Works | None |
| Setup Wizard | /talos/setup | ⚠️ Issues | API tokens in plain text, duplicate skip buttons |
| Prompt Library | /library | ✅ Works | None |
| Skills | /skills | ⚠️ Issues | Duplicate skill cards |
| Agents | /agents | ✅ Works | Minor: truncated description |
| Scheduler | /scheduler | ✅ Works | None |
| Tasks | /tasks | ✅ Works | Minor: red zero for failures |
| Admin | /admin | ⚠️ Issues | Duplicate personalities, dark mode broken |

### Sub-Issues

Individual bugs and UX improvements are filed as sub-issues below.

### LINKED ISSUE #509: [Security] Setup Wizard exposes API tokens in plain text
## Bug: API Tokens Displayed in Plain Text in Setup Wizard

- **URL**: `/talos/setup` (Step 3 — Atlassian)
- **Severity**: 🔴 Critical (Security)

### Description

The Setup Wizard Step 3 (Atlassian) loads previously saved Jira and Confluence Personal Access Tokens and displays them **in plain text** in standard `<input type="text">` fields, not masked `<input type="password">` fields.

### Steps to Reproduce

1. Navigate to `/talos/setup`
2. Select an existing application (GFER)
3. Advance to Step 3 (Atlassian)
4. Observe the "Personal access token vault ref" fields

### Expected

API tokens should be masked (shown as `•••••••••`) in password-type input fields. Tokens should never appear in plain text in the DOM or accessibility tree.

### Actual

Full API token strings are visible in plain text:
- Jira PAT: `OTEyMjIzNDMwMTQ2O...` (visible in DOM and accessibility snapshot)
- Confluence PAT: `NzI2NDMzNTEzNTQyO...` (visible in DOM and accessibility snapshot)

### Impact

- Anyone shoulder-surfing can read credentials
- Screen readers will announce the full token text
- Browser extensions or accessibility tools can extract tokens from the DOM
- Playwright/DOM snapshots capture tokens in plain text

### Fix

1. Change input type from `text` to `password` for all token fields
2. Consider showing only last 4 characters with a "show/hide" toggle
3. Audit all forms for similar credential exposure

### LINKED ISSUE #510: [Bug] Chat page: React hydration mismatch on session ID
## Bug: React Hydration Mismatch on Chat Page

- **URL**: `/chat`
- **Severity**: 🟠 High

### Description

Navigating to `/chat` triggers a React hydration mismatch error. The server-rendered session ID differs from the client-rendered one, causing React to re-render the entire tree.

### Console Error

```
Error: Hydration failed because the server rendered text didn't match the client.
Session 1776084605782 (server) vs Session 1776084605692 (client)
```

### Root Cause

The session ID appears to be generated using `Date.now()` or similar timestamp-based approach that produces different values between SSR and CSR.

### Fix

Generate session IDs on the client only (inside a `useEffect` or with `suppressHydrationWarning`), or use a stable ID source that doesn't change between server and client renders.

### LINKED ISSUE #511: [Bug] Chat: Selecting past sessions doesn't load conversation messages
## Bug: Past Chat Messages Don't Load When Selecting Sessions

- **URL**: `/chat`
- **Severity**: 🟠 High

### Description

Clicking on an existing chat session in the sidebar changes the session ID in the header, but the conversation messages **never load**. The main area continues showing the empty state ("Send a message to start a conversation").

### Steps to Reproduce

1. Navigate to `/chat`
2. Observe multiple sessions in the left sidebar (e.g., "are you there", "are you working", etc.)
3. Click on any session in the sidebar
4. The header updates to show the session's numeric ID
5. The chat area remains empty — no messages are displayed

### Expected

Clicking a session should load and display all messages from that conversation.

### Actual

The empty state persists. Past conversations are effectively inaccessible — they can be listed but not reviewed.

### LINKED ISSUE #512: [Bug] Skills page shows duplicate cards for each skill
## Bug: Duplicate Skill Cards on Skills Page

- **URL**: `/skills`
- **Severity**: 🟠 High

### Description

The Skills page displays each skill card twice with identical content. "Criteria Generator", "Test Planner", and "Test Reviewer" each appear as two separate cards with the same name, description, tags, and tool count.

### Steps to Reproduce

1. Navigate to `/skills`
2. Observe 6 cards displayed
3. Each unique skill appears twice

### Expected

Each skill should appear exactly once.

### Actual

3 unique skills × 2 = 6 cards displayed. This is either a data persistence bug (duplicate records in the store) or a rendering bug (React key issue causing duplicate renders).

### Investigation

Check if the SQLite database / JSON store contains duplicate skill records, or if the data-fetching/rendering logic is mapping data twice.

### LINKED ISSUE #513: [Bug] Admin: Duplicate "Default" personality entries
## Bug: Duplicate Default Personality Entries in Admin

- **URL**: `/admin` → System Personality section
- **Severity**: 🟠 High

### Description

The System Personality section in Admin shows two identical "Default" personality entries, both with "Active" toggles checked and the same system prompt text: "You are Talos, an autonomous test automation assistant."

### Steps to Reproduce

1. Navigate to `/admin`
2. Expand the "System Personality" accordion
3. Observe two "Default" entries with identical content

### Expected

Only one "Default" personality should exist.

### Actual

Two identical "Default" entries displayed. Same root cause pattern as the duplicate Skills bug (#512) — likely a data persistence issue creating duplicate records.

### Related

- #512 — Duplicate skill cards (same duplication pattern)

### LINKED ISSUE #514: [Bug] Dark theme toggle doesn't apply dark mode
## Bug: Dark Theme Toggle Doesn't Apply

- **URL**: Any page — uses the navbar theme toggle
- **Severity**: 🟡 Medium

### Description

Clicking the theme toggle button in the navbar and selecting "Dark" does not change the page appearance. The toggle button icon updates but the page remains in light mode.

### Steps to Reproduce

1. Click the gear/sun icon in the top-right navbar
2. The dropdown shows: Light, Dark, System
3. Click "Dark"
4. The dropdown closes but the page remains in light mode — no dark background, no color inversion

### Expected

Selecting "Dark" should apply a dark color scheme to the entire application.

### Actual

No visual change. The page remains in light mode regardless of the selection.

### LINKED ISSUE #515: [UX] Chat: Raw numeric session ID in header instead of meaningful title
## UX: Chat Session Header Shows Raw Numeric ID

- **URL**: `/chat`
- **Severity**: 🟡 Medium (UX)

### Description

The chat header displays "Session 1776084605809" — a raw numeric timestamp — instead of a human-readable title. This makes it impossible to identify what a conversation is about at a glance.

### Current Behavior

Header shows: `Session 1776084605809`

### Suggested Improvement

- Use the first message text as the session title (already done in the sidebar)
- Or generate a short AI summary
- Fallback to "New Conversation" for empty sessions
- Format: `are you there — Apr 1, 2026` instead of `Session 1776084605809`

### LINKED ISSUE #516: [UX] Dashboard: Database type and JDBC URL concatenated without separator
## UX: Dashboard Database Names Concatenated with JDBC URLs

- **URL**: `/talos` (Dashboard — App Intelligence → Detected Databases)
- **Severity**: 🟡 Medium (UX)

### Description

In the Detected Databases section, the database type and JDBC URL are concatenated without any separator, making them hard to read:

- `MySQLjdbc:mysql://localhost:3306/yourdb`
- `Oraclejdbc:oracle:thin:@kdcumisd1.nyiso.com:1526/miskdvd1`

### Suggested Fix

Add visual separation between the database type label and the connection URL:
- Show type as a badge/tag above or before the URL
- Add a line break between type and URL
- Use a styled format: **MySQL** — `jdbc:mysql://localhost:3306/yourdb`

### LINKED ISSUE #517: [UX] Setup Wizard: Redundant skip buttons on multiple steps
## UX: Setup Wizard Has Redundant Skip Buttons

- **URL**: `/talos/setup`
- **Severity**: 🟢 Low (UX)

### Description

Several Setup Wizard steps display **two or three** ways to skip the current step:

1. "Skip — Continue to Next Step" button inside the step content area
2. "Skip This Step" button in the step content (on the Upload Docs step)
3. "Skip >" button in the bottom-right navigation bar

Having multiple skip affordances in different locations is confusing and clutters the interface.

### Suggested Fix

Standardize to a single skip mechanism:
- Keep only the bottom navigation "Skip" button (consistent with "Back" on the left)
- Remove the in-content skip buttons
- Or consolidate into a single "Skip" in the step content and remove the bottom bar Skip

### LINKED ISSUE #518: [UX] Setup Wizard: Step tabs truncated with no scroll indicator
## UX: Setup Wizard Step Tabs Truncated Without Scroll Indicator

- **URL**: `/talos/setup`
- **Severity**: 🟢 Low (UX)

### Description

The setup wizard has 9 steps displayed as horizontal tabs, but on standard viewport widths (1280px), steps 8 and 9 ("Review Criteria" and "Generate Tests") are cut off and not visible without horizontal scrolling. There is no visual indicator (scroll shadow, arrow, or fade effect) to tell users that more steps exist.

### Suggested Fix

- Add horizontal scroll indicators (fade edges or arrow buttons)
- Or make the step tabs responsive (wrap to multiple rows on smaller viewports)
- Or use a compact step indicator design (numbers only, full labels on hover)

### LINKED ISSUE #519: [UX] Task Queue: Failed count styled red when value is zero
## UX: Task Queue Shows Failed Count in Red When Zero

- **URL**: `/tasks`
- **Severity**: 🟢 Low (UX)

### Description

The Task Queue stats cards show a "Failed" count styled in red even when the value is 0. This creates unnecessary visual alarm and implies there's a problem when there isn't one.

### Current Behavior

The "0" under "Failed" is displayed with red styling, making it look alarming at a glance.

### Suggested Fix

- Show 0 in neutral/muted color for all stats
- Only apply red/error styling when the count is > 0
- Same pattern should apply to other status colors (green for Completed should only be highlighted when > 0)

### LINKED ISSUE #520: [Bug] Missing favicon.ico returns 404 on every page load
## UX: Missing Favicon Returns 404

- **URL**: All pages
- **Severity**: 🟢 Low

### Description

Every page load triggers a console error:
```
Failed to load resource: the server responded with a status of 404 (Not Found) @ http://localhost:3001/favicon.ico
```

### Fix

Add a `favicon.ico` file to the `ui/public/` directory, or add a `<link rel="icon">` tag in the layout to point to the Talos logo.

### LINKED ISSUE #521: [UX] Form dialogs lack required field indicators
## UX: Form Dialogs Lack Required Field Indicators

- **URL**: Multiple pages — Add Application (`/talos`), Add Vault Role (`/talos/vault`)
- **Severity**: 🟢 Low (UX)

### Description

Form dialogs like "Add Application" and "Add Vault Role" don't indicate which fields are required. Users have to experiment to discover that the button enables after filling certain fields. 

For example, the "Add Application" dialog's submit button becomes enabled after filling only the "Application Name" field, but there's no asterisk, "(required)" label, or other indicator on that field.

### Suggested Fix

- Add asterisks (*) or "(required)" labels to mandatory fields
- Add helper text below optional fields saying "(optional)"
- Show inline validation messages when required fields are empty and user attempts to submit

### LINKED ISSUE #522: [UX] Agents page truncates description with no way to see full text
## UX: Agents Page Truncates Agent Description Without Expand Option

- **URL**: `/agents`
- **Severity**: 🟢 Low (UX)

### Description

The "Test Orchestrator" agent card truncates its description after about one line. The full description is: "Coordinates the full autonomous testing lifecycle: ingest requirement..." (truncated). There's no expand button, tooltip, or hover to reveal the full text.

### Suggested Fix

- Add a "Show more" link or expandable section
- Or show the full text on hover via a tooltip
- Or allow card expansion on click

### PR DESCRIPTION
**Pull request by mgcronin**
## Summary

Resolves all 14 sub-issues from the UI Walkthrough Epic (#508). Changes span security fixes, bug fixes, and UX improvements across 10 UI components.

### Security Fixes
- **#509** — API tokens in Atlassian Settings now use `type="password"` inputs to prevent shoulder-surfing and DOM exposure

### Bug Fixes
- **#510** — Chat page hydration mismatch fixed: session IDs generated client-side via `useEffect` instead of `Date.now()` at initialization
- **#511** — Past chat messages now load when switching sessions by calling `getChatSession()` API
- **#512** — Duplicate skill cards eliminated via ID-based deduplication before render
- **#513** — Duplicate personality entries eliminated via ID-based deduplication in Admin panel
- **#514** — Dark theme toggle: hardened CSS selector specificity with `:root.dark` alongside `.dark`
- **#520** — Added SVG favicon to `ui/public/` — eliminates 404 on every page load

### UX Improvements
- **#515** — Chat header shows session title (preview text) instead of raw numeric timestamp ID
- **#516** — Dashboard: database type now renders as a badge with clear separation from JDBC URL
- **#517** — Setup Wizard: removed redundant in-content skip buttons (Data Sources, Atlassian steps); bottom nav "Skip" is the single mechanism
- **#518** — Setup Wizard: step progress bar now scrolls horizontally with CSS mask fade indicators for overflow
- **#519** — Task Queue: zero-count stat values use muted grey styling instead of colored (e.g., red for Failed=0)
- **#521** — Form dialogs: required fields now show asterisk (`*`) indicators; optional fields show "(optional)" label
- **#522** — Agent cards: truncated descriptions now have "Show more" expand link

### Test Coverage
- Updated existing tests for chat, skills, and admin pages
- Added new test files for tasks page (`page.test.tsx`) and agents page (`page.test.tsx`)
- All 92 UI tests pass, all 1509 backend tests pass
- Lint clean, typecheck clean, Next.js build succeeds

Closes #508
Closes #509
Closes #510
Closes #511
Closes #512
Closes #513
Closes #514
Closes #515
Closes #516
Closes #517
Closes #518
Closes #519
Closes #520
Closes #521
Closes #522

### CODE REVIEW

File: ui/app/chat/page.tsx [hunk 1]
```diff
@@ -1,13 +1,16 @@
...
+import { useQuery } from "@tanstack/react-query";
 import { useSocket } from "@/lib/socket";
+import { getChatSession } from "@/lib/api";
 import { Button } from "@/components/ui/button";
 import { Input } from "@/components/ui/input";
 import { Card, CardContent } from "@/components/ui/card";
 import { SessionSidebar } from "@/components/talos/session-sidebar";
 import { ChatHeader } from "@/components/talos/chat-header";
 import { RagContextIndicator } from "@/components/talos/rag-context-indicator";
+import { getChatSessions } from "@/lib/api";
```
Comment (mgcronin) [inline ui/app/chat/page.tsx:13]: nit: Duplicate import from `@/lib/api` — `getChatSession` (line 6) and `getChatSessions` (line 13) should be merged into a single import statement:

```typescript
import { getChatSession, getChatSessions } from "@/lib/api";
```

Not blocking, but keeps imports tidy.

File: ui/components/talos/setup-wizard.tsx [hunk 2]
```diff
@@ -156,16 +156,17 @@ export function SetupWizard() {
 
   return (
     <div className="space-y-6">
-      {/* Progress Bar */}
-      <div className="flex items-center gap-2">
+      {/* Progress Bar — scrollable with fade indicators (#518) */}
+      <div className="relative">
+        <div className="flex items-center gap-2 overflow-x-auto pb-2 scrollbar-thin" style={{ maskImage: "linear-gradient(to right, transparent 0, black 8px, black calc(100% - 24px), transparent 100%)", WebkitMaskImage: "linear-gradient(to right, transparent 0, black 8px, black calc(100% - 24px), transparent 100%)" }}>
         {STEPS.map((step, i) => {
```
Comment (mgcronin) [inline ui/components/talos/setup-wizard.tsx:162]: nit: This long inline `style` attribute works but is a bit gnarly to read. Consider extracting to a CSS class or Tailwind arbitrary value:

```tsx
className="flex items-center gap-2 overflow-x-auto pb-2 scrollbar-thin [mask-image:linear-gradient(to_right,transparent_0,black_8px,black_calc(100%-24px),transparent_100%)]"
```

Minor readability suggestion — not blocking.

File: ui/app/agents/page.tsx [hunk 3]
```diff
@@ -129,14 +129,29 @@ function AgentCard({
...
+            {!expanded && agent.description && agent.description.length > 80 && (
+              <button
+                className="text-xs text-primary hover:underline mt-0.5"
+                onClick={() => setExpanded(true)}
+              >
+                Show more
+              </button>
+            )}
           </div>
           <Switch checked={agent.enabled} onCheckedChange={onToggle} />
```
Comment (mgcronin) [inline ui/app/agents/page.tsx:156]: nit: The magic number `80` for the "Show more" threshold doesn't perfectly correlate with `line-clamp-2` — a description slightly under 80 chars could still be truncated depending on container width and font metrics. Consider extracting this to a named constant (`DESCRIPTION_EXPAND_THRESHOLD`) for clarity, or alternatively detecting overflow via a `ref` + `scrollHeight > clientHeight` check. Not blocking — the heuristic works well enough in practice.

**Review by mgcronin — COMMENTED** [review]
## Code Review Summary — PR #523

**Epic:** #508 — UI Walkthrough: Bugs & UX Issues (April 2026)
**Scope:** 14 sub-issues (#509–#522), 24 changed files, +1310 / −45

---

### Requirements: ✅ PASS — All 14 sub-issues addressed

| Sub-Issue | Title | Status |
|-----------|-------|--------|
| #509 | Setup Wizard token masking (CRITICAL security) | ✅ `type="password"` on all 4 token inputs |
| #510 | Chat hydration mismatch | ✅ `useId()` + empty initial state |
| #511 | Chat past messages loading | ✅ `getChatSession()` on session select |
| #512 | Skills deduplication | ✅ ID-based `filter` + `findIndex` |
| #513 | Admin personality deduplication | ✅ Same dedup pattern |
| #514 | Dark theme toggle | ✅ `:root.dark` CSS selector added |
| #515 | Chat conversation titles | ✅ `sessionTitle` prop from preview/first message |
| #516 | Dashboard DB type separator | ✅ `<Badge>` component replaces inline text |
| #517 | Setup Wizard skip button cleanup | ✅ Two redundant skip buttons removed |
| #518 | Setup Wizard step tabs scroll | ✅ `overflow-x-auto` + mask gradient + `min-w` |
| #519 | Task Queue failed count styling | ✅ Conditional color based on `value > 0` |
| #520 | Favicon addition | ✅ SVG favicon + layout.tsx reference updated |
| #521 | Required field indicators | ✅ Asterisks + "(optional)" labels |
| #522 | Agent description expand/collapse | ✅ `expanded` state + "Show more" button |

No scope creep detected. Each change maps directly to a sub-issue.

---

### Security: ✅ CLEAN

**OWASP Top 10 Manual Scan — No findings.**

| Category | Status |
|----------|--------|
| A01: Broken Access Control | No auth changes introduced |
| A02: Cryptographic Failures | ✅ #509 fixes plaintext token exposure → `type="password"` |
| A03: Injection | No `dangerouslySetInnerHTML`, `eval()`, or `innerHTML` — React escaping handles all user text |
| A04: Insecure Design | No new trust boundaries or rate-limiting gaps |
| A05: Security Misconfiguration | No debug modes, verbose errors, or default creds |
| A06: Vulnerable Components | No new dependencies added |
| A07: Auth Failures | No auth changes |
| A08: Data Integrity | No deserialization changes |
| A09: Logging Failures | No logging changes |
| A10: SSRF | No server-side URL consumption from user input |

The critical security fix (#509) is correctly implemented — all 4 token fields (Jira API token, Jira PAT, Confluence API token, Confluence PAT) now use `type="password"`.

---

### Security Scanners: ✅ CLEAN

CodeQL ran on this PR (3 checks: Analyze actions, Analyze JS/TS, CodeQL required status). All passed with no findings. No `github-advanced-security` bot comments exist.

---

### Code Quality: ✅ GOOD (3 nits, 0 blockers)

- **Architecture**: Solid. Dedup pattern is consistent across skills and admin. Hydration fix with `useId()` is the correct React approach.
- **Naming**: Clear and descriptive throughout.
- **Consistency**: New code follows existing patterns (react-query, Tailwind, shadcn/ui components).
- **DRY**: Dedup logic is repeated in skills and admin — acceptable since they operate on different types.
- **Error handling**: `handleSelectSession` has a try/catch for session fetch failures — gracefully falls back to empty state.

**Nits (see inline comments):**
1. Duplicate `@/lib/api` import in `chat/page.tsx` (lines 6 + 13)
2. Magic number `80` for agent description expand threshold
3. Inline `style` on setup wizard scrollable container

---

### Performance: ✅ CLEAN

- `getChatSessions` polled every 10s — appropriate for chat.
- Dedup via `findIndex` is O(n²) but arrays are tiny (<100 items). No concern.
- No N+1 queries, no unbounded fetches, no memory leaks, no missing cleanup.

---

### Tests: ✅ SUFFICIENT

- **New unit tests**: `agents/page.test.tsx` (3 tests), `tasks/page.test.tsx` (3 tests)
- **Updated unit tests**: `admin/page.test.tsx`, `chat/page.test.tsx`, `skills/page.test.tsx`
- **New E2E tests**: `epic-508-ui-fixes.spec.ts` — 24 Playwright tests covering all 14 sub-issues
- **New page objects**: `agents.page.ts`, `tasks.page.ts` — follows existing POM pattern
- **Quality**: Good use of mocks, async patterns, meaningful assertions, `test.step()` grouping
- PR claims: 92 UI unit tests pass, 1509 backend tests pass, 147 Playwright e2e tests pass

---

### Documentation: ✅ UP TO DATE

- **CHANGELOG.md**: ✅ Updated under `### Fixed` (7 entries) and `### Changed` (6 entries) with all 14 sub-issues
- **docs/ARCHITECTURE.md**: No structural changes needed — no new modules, endpoints, or data models
- **docs/USER_GUIDE.md**: No user-facing workflow changes that require guide updates
- **test-setup.ts**: Correctly added `scrollIntoView` stub for jsdom compatibility

---

### CI Status: ✅ ALL GREEN

| Job | Status | Notes |
|-----|--------|-------|
| CI/api (pull_request) | ✅ Passed (38s) | — |
| CI/ui (pull_request) | ✅ Passed (56s) | — |
| CodeQL/Analyze (actions) | ✅ Passed (40s) | — |
| CodeQL/Analyze (javascript-typescript) | ✅ Passed (1m12s) | — |
| CodeQL (required) | ✅ Passed (2s) | — |

---

### Prior Review Comments: 0 total, 0 unresolved

No prior reviews, review comments, or PR-level comments from humans, Copilot, or bots.

---

### Verdict: APPROVE ✅

_(Submitted as COMMENT because GitHub prevents approving your own PR — but the intent is APPROVE.)_

Well, well, well... I have to hand it to you — this is disturbingly competent work. All 14 sub-issues addressed, the CRITICAL security fix (#509) is correctly implemented, zero OWASP findings, 24 e2e tests added with proper page objects, all 5 CI checks green, and the CHANGELOG is actually up to date. I almost feel disappointed that I couldn't find a real vulnerability to mock you about.

The three nits I left are cosmetic — a duplicate import, a magic number, and an inline style. None are blocking. The dedup pattern with `findIndex` is O(n²), which would normally trigger my "did you learn algorithmic complexity from a fortune cookie?" reflex, but given arrays of 5-10 items, I'll suppress it... this time.

**Ship it.**
